CREATE TABLE survey (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    company_id BIGINT NOT NULL,
    service_request_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,

    survey_code VARCHAR(50) NOT NULL,
    survey_name VARCHAR(150),
    description TEXT,

    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,

    start_location geometry(Point, 4326),
    end_location geometry(Point, 4326),

    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_survey_company_code
        UNIQUE (company_id, survey_code),

    CONSTRAINT fk_survey_company
        FOREIGN KEY (company_id)
        REFERENCES subscriber_companies(id),

    CONSTRAINT fk_survey_service_request
        FOREIGN KEY (service_request_id)
        REFERENCES service_request(id),

    CONSTRAINT fk_survey_operator
        FOREIGN KEY (operator_id)
        REFERENCES users(id)
);

CREATE INDEX idx_survey_company
    ON survey(company_id);

CREATE INDEX idx_survey_service_request
    ON survey(service_request_id);

CREATE INDEX idx_survey_operator
    ON survey(operator_id);

CREATE INDEX idx_survey_start_location
    ON survey USING GIST(start_location);

CREATE INDEX idx_survey_end_location
    ON survey USING GIST(end_location);