CREATE TABLE survey_data (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    survey_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,

    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(100),
    file_size BIGINT,
    record_count BIGINT,

    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_survey_data_survey
        FOREIGN KEY (survey_id)
        REFERENCES survey(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_survey_data_company
        FOREIGN KEY (company_id)
        REFERENCES subscriber_companies(id),

    CONSTRAINT fk_survey_data_uploaded_by
        FOREIGN KEY (uploaded_by)
        REFERENCES users(id)
);

CREATE INDEX idx_survey_data_survey
    ON survey_data(survey_id);

CREATE INDEX idx_survey_data_company
    ON survey_data(company_id);

CREATE INDEX idx_survey_data_uploaded_by
    ON survey_data(uploaded_by);