CREATE TABLE processed_magnetic_data (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    survey_id BIGINT NOT NULL,
    survey_data_id BIGINT NOT NULL,

    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(100),
    file_size BIGINT,
    record_count BIGINT,

    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_processed_magnetic_survey
        FOREIGN KEY (survey_id)
        REFERENCES survey(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_processed_magnetic_survey_data
        FOREIGN KEY (survey_data_id)
        REFERENCES survey_data(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_processed_magnetic_survey
    ON processed_magnetic_data(survey_id);

CREATE INDEX idx_processed_magnetic_survey_data
    ON processed_magnetic_data(survey_data_id);