CREATE TABLE magnetic_anomaly_map (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    survey_id BIGINT NOT NULL,
    processed_magnetic_data_id BIGINT NOT NULL,

    map_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(100),
    file_size BIGINT,

    generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_anomaly_map_survey
        FOREIGN KEY (survey_id)
        REFERENCES survey(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_anomaly_map_processed_data
        FOREIGN KEY (processed_magnetic_data_id)
        REFERENCES processed_magnetic_data(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_anomaly_map_survey
    ON magnetic_anomaly_map(survey_id);

CREATE INDEX idx_anomaly_map_processed_data
    ON magnetic_anomaly_map(processed_magnetic_data_id);