CREATE TABLE map_review (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    magnetic_anomaly_map_id BIGINT NOT NULL,
    geologist_id BIGINT NOT NULL,

    decision VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    comment TEXT,

    reviewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_map_review_map
        FOREIGN KEY (magnetic_anomaly_map_id)
        REFERENCES magnetic_anomaly_map(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_map_review_geologist
        FOREIGN KEY (geologist_id)
        REFERENCES users(id)
);

CREATE INDEX idx_map_review_map
    ON map_review(magnetic_anomaly_map_id);

CREATE INDEX idx_map_review_geologist
    ON map_review(geologist_id);