CREATE TABLE ai_analysis (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    survey_id BIGINT NOT NULL,
    magnetic_anomaly_map_id BIGINT NOT NULL,

    analysis_result TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ai_analysis_survey
        FOREIGN KEY (survey_id)
        REFERENCES survey(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ai_analysis_map
        FOREIGN KEY (magnetic_anomaly_map_id)
        REFERENCES magnetic_anomaly_map(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_ai_analysis_survey
    ON ai_analysis(survey_id);

CREATE INDEX idx_ai_analysis_map
    ON ai_analysis(magnetic_anomaly_map_id);