CREATE TABLE report (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    survey_id BIGINT NOT NULL,
    ai_analysis_id BIGINT NOT NULL,

    report_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(100),
    file_size BIGINT,

    generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_report_survey
        FOREIGN KEY (survey_id)
        REFERENCES survey(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_report_ai_analysis
        FOREIGN KEY (ai_analysis_id)
        REFERENCES ai_analysis(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_report_survey
    ON report(survey_id);

CREATE INDEX idx_report_ai_analysis
    ON report(ai_analysis_id);