ALTER TABLE service_request
    ADD COLUMN operator_id BIGINT REFERENCES users(id),
    ADD COLUMN operator_decision_reason TEXT;

ALTER TABLE survey
    ALTER COLUMN started_at DROP NOT NULL,
    ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN equipment_used TEXT,
    ADD COLUMN completed_bounds geometry(Polygon, 4326);

CREATE INDEX idx_service_request_operator ON service_request(operator_id);
CREATE INDEX idx_survey_completed_bounds ON survey USING GIST(completed_bounds);

CREATE TABLE management_notification (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT NOT NULL REFERENCES subscriber_companies(id),
    notification_type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_management_notification_company_created
    ON management_notification(company_id, created_at DESC);
