-- V4: Create farms and farm blocks

-- ============================================
-- FARMS
-- ============================================

CREATE TABLE farms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    description VARCHAR(500),

    location geometry(Point, 4326),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    area_hectares DOUBLE PRECISION,

    customer_id BIGINT NOT NULL,

    CONSTRAINT fk_farms_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_farms_customer_id
    ON farms(customer_id);

CREATE INDEX idx_farms_location
    ON farms
    USING GIST(location);


-- ============================================
-- FARM BLOCKS
-- ============================================

CREATE TABLE farm_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    area_hectares DOUBLE PRECISION,

    center_latitude DOUBLE PRECISION,

    center_longitude DOUBLE PRECISION,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    description VARCHAR(500),

    name VARCHAR(150) NOT NULL,

    updated_at TIMESTAMP,

    farm_id BIGINT NOT NULL,

    CONSTRAINT fk_farm_blocks_farm
        FOREIGN KEY (farm_id)
        REFERENCES farms(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_blocks_farm_id
    ON farm_blocks(farm_id);