CREATE TABLE agriculture_reports (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES subscriber_companies(id),
    mission_id BIGINT NOT NULL UNIQUE REFERENCES missions(id),
    report_code VARCHAR(40) NOT NULL UNIQUE,
    application_date DATE NOT NULL,
    operator_license VARCHAR(80),
    crop_type VARCHAR(150) NOT NULL,
    growth_stage VARCHAR(100),
    total_area_treated_ha NUMERIC(12,2),
    target_problem TEXT,
    application_start_time VARCHAR(20),
    application_end_time VARCHAR(20),
    temperature_c NUMERIC(6,2),
    wind_speed_kmh NUMERIC(6,2),
    wind_direction VARCHAR(40),
    relative_humidity NUMERIC(6,2),
    sky_conditions VARCHAR(120),
    rain_forecast VARCHAR(200),
    trade_name VARCHAR(150),
    registration_number VARCHAR(100),
    active_ingredient VARCHAR(200),
    total_product_used_l NUMERIC(12,2),
    total_water_volume_l NUMERIC(12,2),
    product_rate_l_ha NUMERIC(12,4),
    water_rate_l_ha NUMERIC(12,4),
    adjuvants TEXT,
    equipment_used VARCHAR(200),
    nozzle_type VARCHAR(200),
    droplet_size_microns NUMERIC(8,2),
    pre_harvest_interval_days INTEGER,
    restricted_entry_interval_hours INTEGER,
    buffer_zone_notes TEXT,
    coverage_quality VARCHAR(100),
    coverage_observations TEXT,
    incidents_notes TEXT,
    next_scout_date DATE,
    applicator_signature VARCHAR(150),
    photo_1_path VARCHAR(500),
    photo_2_path VARCHAR(500),
    finalized BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_agriculture_reports_company ON agriculture_reports(company_id);
CREATE INDEX idx_agriculture_reports_mission ON agriculture_reports(mission_id);
